/*
 * File: segments.h
 * File Created: 01 Jun 2026
 * Author: BjornBEs
 * -----
 * Last Modified: 07 Jul 2026
 * Modified By: BjornBEs
 * -----
 */

#pragma once

#define SEGMENT_SELECTOR(n)  (n * 8)

#define KERNEL_CODE_INDEX    1
#define KERNEL_DATA_INDEX    2
#define UNUSED_INDEX         3
#define USER_DATA_INDEX      4
#define USER_CODE_INDEX      5
#define UNUSED32_INDEX       6
#define USER_CODE32_INDEX    7
#define USER_DATA32_INDEX    8
#define TSS_INDEX            9

#define KERNEL_CODE_SELECTOR SEGMENT_SELECTOR(KERNEL_CODE_INDEX)
#define KERNEL_DATA_SELECTOR SEGMENT_SELECTOR(KERNEL_DATA_INDEX)
#define UNUSED_SELECTOR      SEGMENT_SELECTOR(UNUSED_INDEX)
#define USER_DATA_SELECTOR   SEGMENT_SELECTOR(USER_DATA_INDEX)
#define USER_CODE_SELECTOR   SEGMENT_SELECTOR(USER_CODE_INDEX)
#define UNUSED32_SELECTOR    SEGMENT_SELECTOR(UNUSED32_INDEX)
#define USER_CODE32_SELECTOR SEGMENT_SELECTOR(USER_CODE32_INDEX)
#define USER_DATA32_SELECTOR SEGMENT_SELECTOR(USER_DATA32_INDEX)
#define TSS_SELECTOR         SEGMENT_SELECTOR(TSS_INDEX)
