/* AUTO-GENERATED FILE - DO NOT EDIT BY HAND
 * Generated from config/config.env by scripts/gen_config.sh
 */
#pragma once

#define CONFIG_TARGET 64
#define CONFIG_ARCH "x86_64"
#define CONFIG_IMAGETYPE "disk"
#define CONFIG_IMAGEFS "fat32"
#define CONFIG_IMAGESIZE "250m"
#define CONFIG_TOOLCHAIN "toolchains"
#define CONFIG_MOUNTMETHOD "mount"
#define CONFIG_USE_BIOS 1
#define CONFIG_ENABLE_MULTI_CORE 1
#define CONFIG_MAX_PATH_LENGTH 512
#define CONFIG_BAREOS_VERSION 0x0010000
#define CONFIG_POSIX_VERSION 202405L
#define CONFIG_USE_POSIX_SYS 0
#define CONFIG_ENABLE_PAGING 1
#define CONFIG_USE_EAGER_FORK 0
#define CONFIG_MODULE_BSW 1
#define CONFIG_MODULE_LA57 0
#define CONFIG_INCLUDE_MLFQ 1
#define CONFIG_SCHED_ALGORITHM "MLFQ"
#define CONFIG_PROCESS_MAX 64
#define CONFIG_PROCESS_MAX_OPEN_FD 64
#define CONFIG_PROCESS_MAX_THREADS 2
#define CONFIG_PROCESS_MAX_SECTIONS 10
#define CONFIG_EXEC_MAX_ARGS 64
#define CONFIG_LOADER_MAX_NOTES 8
#define CONFIG_LOADER_MAX_INTERPRETERS 8
#define CONFIG_LOADER_MAX_SECTIONS 64
#define CONFIG_LOADER_MAX_SYMBOLS 64
#define CONFIG_LOADER_MAX_SECTION_NAME_LENGTH 64
#define CONFIG_USE_LEVEL_1 1
#define CONFIG_USE_LEVEL_2 1
#define CONFIG_USE_LEVEL_3 1
#define CONFIG_USE_LEVEL_4 1
#define CONFIG_USE_LEVEL_5 1
