/*
 * File: printf_config.h
 * File Created: 20 Jan 2026
 * Author: BjornBEs
 * -----
 * Last Modified: 05 Mar 2026
 * Modified By: BjornBEs
 * -----
 */

#define PRINTF_INTEGER_BUFFER_SIZE 32
#define PRINTF_DECIMAL_BUFFER_SIZE 32
#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 0
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS 0
#define PRINTF_SUPPORT_LONG_LONG 1
#define PRINTF_SUPPORT_WRITEBACK_SPECIFIER 0
#define PRINTF_DEFAULT_FLOAT_PRECISION 6
#define PRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL 9
#define PRINTF_LOG10_TAYLOR_TERMS 4
#define PRINTF_CHECK_FOR_NUL_IN_FORMAT_SPECIFIER 1