/*
 * File: winternl.h
 * File Created: 26 Jun 2026
 * Author: BjornBEs
 * -----
 * Last Modified: 26 Jun 2026
 * Modified By: BjornBEs
 * -----
 */

#pragma once

#include "ntdef.h"
#include "windef.h"
#include "winternl_alpc.h"
#include "winternl_ldr.h"
#include "winternl_rtl.h"
#include "winternl_types.h"

/*
 * Internal NT APIs and data structures
 *
 * Copyright (C) the Wine project
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

/***********************************************************************
 * Function declarations
 */

NTSYSAPI NTSTATUS WINAPI ApiSetQueryApiSetPresence(const UNICODE_STRING *, BOOLEAN *);
NTSYSAPI NTSTATUS WINAPI ApiSetQueryApiSetPresenceEx(const UNICODE_STRING *, BOOLEAN *, BOOLEAN *);
NTSYSAPI void WINAPI DbgBreakPoint(void);
NTSYSAPI NTSTATUS WINAPIV DbgPrint(LPCSTR fmt, ...);
NTSYSAPI NTSTATUS WINAPIV DbgPrintEx(ULONG iComponentId, ULONG Level, LPCSTR fmt, ...);
NTSYSAPI NTSTATUS WINAPI DbgUiConnectToDbg(void);
NTSYSAPI NTSTATUS WINAPI DbgUiContinue(CLIENT_ID *, NTSTATUS);
NTSYSAPI NTSTATUS WINAPI DbgUiConvertStateChangeStructure(DBGUI_WAIT_STATE_CHANGE *, struct _DEBUG_EVENT *);
NTSYSAPI NTSTATUS WINAPI DbgUiDebugActiveProcess(HANDLE);
NTSYSAPI HANDLE WINAPI DbgUiGetThreadDebugObject(void);
NTSYSAPI NTSTATUS WINAPI DbgUiIssueRemoteBreakin(HANDLE);
NTSYSAPI void WINAPI DbgUiRemoteBreakin(void *);
NTSYSAPI void WINAPI     DbgUiSetThreadDebugObject(HANDLE);
NTSYSAPI NTSTATUS WINAPI DbgUiStopDebugging(HANDLE);
NTSYSAPI NTSTATUS WINAPI DbgUiWaitStateChange(DBGUI_WAIT_STATE_CHANGE *, LARGE_INTEGER *);
NTSYSAPI void WINAPI DbgUserBreakPoint(void);

NTSYSAPI NTSTATUS WINAPI LdrQueryProcessModuleInformation(RTL_PROCESS_MODULES *, ULONG, ULONG *);

NTSYSAPI NTSTATUS WINAPI NtAcceptConnectPort(PHANDLE, ULONG, PLPC_MESSAGE, BOOLEAN, PLPC_SECTION_WRITE, PLPC_SECTION_READ);
NTSYSAPI NTSTATUS WINAPI NtAccessCheck(PSECURITY_DESCRIPTOR, HANDLE, ACCESS_MASK, PGENERIC_MAPPING, PPRIVILEGE_SET, PULONG, PULONG, NTSTATUS *);
NTSYSAPI NTSTATUS WINAPI NtAccessCheckAndAuditAlarm(UNICODE_STRING *, HANDLE, UNICODE_STRING *, UNICODE_STRING *, PSECURITY_DESCRIPTOR, ACCESS_MASK, GENERIC_MAPPING *, BOOLEAN, ACCESS_MASK *, NTSTATUS *, BOOLEAN *);
NTSYSAPI NTSTATUS WINAPI NtAccessCheckByTypeAndAuditAlarm(UNICODE_STRING *, HANDLE, UNICODE_STRING *, UNICODE_STRING *, PSECURITY_DESCRIPTOR, PSID, ACCESS_MASK, AUDIT_EVENT_TYPE, ULONG, OBJECT_TYPE_LIST *, ULONG, GENERIC_MAPPING *, BOOLEAN, ACCESS_MASK *, NTSTATUS *, BOOLEAN *);
NTSYSAPI NTSTATUS WINAPI NtAddAtom(const WCHAR *, ULONG, RTL_ATOM *);
NTSYSAPI NTSTATUS WINAPI NtAdjustGroupsToken(HANDLE, BOOLEAN, PTOKEN_GROUPS, ULONG, PTOKEN_GROUPS, PULONG);
NTSYSAPI NTSTATUS WINAPI NtAdjustPrivilegesToken(HANDLE, BOOLEAN, PTOKEN_PRIVILEGES, DWORD, PTOKEN_PRIVILEGES, PDWORD);
NTSYSAPI NTSTATUS WINAPI NtAlertMultipleThreadByThreadId(HANDLE *, ULONG, void *, void *);
NTSYSAPI NTSTATUS WINAPI NtAlertResumeThread(HANDLE, PULONG);
NTSYSAPI NTSTATUS WINAPI NtAlertThread(HANDLE ThreadHandle);
NTSYSAPI NTSTATUS WINAPI NtAlertThreadByThreadId(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtAllocateLocallyUniqueId(PLUID lpLuid);
NTSYSAPI NTSTATUS WINAPI NtAllocateReserveObject(HANDLE *handle, const OBJECT_ATTRIBUTES *attr, MEMORY_RESERVE_OBJECT_TYPE type);
NTSYSAPI NTSTATUS WINAPI NtAllocateUuids(PULARGE_INTEGER, PULONG, PULONG, PUCHAR);
NTSYSAPI NTSTATUS WINAPI NtAllocateVirtualMemory(HANDLE, PVOID *, ULONG_PTR, SIZE_T *, ULONG, ULONG);
NTSYSAPI NTSTATUS WINAPI NtAllocateVirtualMemoryEx(HANDLE, PVOID *, SIZE_T *, ULONG, ULONG, MEM_EXTENDED_PARAMETER *, ULONG);

NTSYSAPI NTSTATUS WINAPI NtAreMappedFilesTheSame(PVOID, PVOID);
NTSYSAPI NTSTATUS WINAPI NtAssignProcessToJobObject(HANDLE, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtCallbackReturn(PVOID, ULONG, NTSTATUS);
NTSYSAPI NTSTATUS WINAPI NtCancelIoFile(HANDLE, PIO_STATUS_BLOCK);
NTSYSAPI NTSTATUS WINAPI NtCancelIoFileEx(HANDLE, PIO_STATUS_BLOCK, PIO_STATUS_BLOCK);
NTSYSAPI NTSTATUS WINAPI NtCancelSynchronousIoFile(HANDLE, PIO_STATUS_BLOCK, PIO_STATUS_BLOCK);
NTSYSAPI NTSTATUS WINAPI NtCancelTimer(HANDLE, BOOLEAN *);
NTSYSAPI NTSTATUS WINAPI NtClearEvent(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtClose(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtCloseObjectAuditAlarm(PUNICODE_STRING, HANDLE, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtCommitTransaction(HANDLE, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtCompareObjects(HANDLE, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtCompareTokens(HANDLE, HANDLE, BOOLEAN *);
NTSYSAPI NTSTATUS WINAPI NtCompleteConnectPort(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtConnectPort(PHANDLE, PUNICODE_STRING, PSECURITY_QUALITY_OF_SERVICE, PLPC_SECTION_WRITE, PLPC_SECTION_READ, PULONG, PVOID, PULONG);
NTSYSAPI NTSTATUS WINAPI NtContinue(PCONTEXT, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtContinueEx(CONTEXT *, KCONTINUE_ARGUMENT *);
NTSYSAPI NTSTATUS WINAPI NtConvertBetweenAuxiliaryCounterAndPerformanceCounter(ULONG, ULONGLONG *, ULONGLONG *, ULONGLONG *);
NTSYSAPI NTSTATUS WINAPI NtCreateDebugObject(HANDLE *, ACCESS_MASK, OBJECT_ATTRIBUTES *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtCreateDirectoryObject(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSYSAPI NTSTATUS WINAPI NtCreateEvent(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, EVENT_TYPE, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtCreateEventPair(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSYSAPI NTSTATUS WINAPI NtCreateFile(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, PIO_STATUS_BLOCK, PLARGE_INTEGER, ULONG, ULONG, ULONG, ULONG, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtCreateIoCompletion(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, ULONG);
NTSYSAPI NTSTATUS WINAPI NtCreateJobObject(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtCreateKey(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, ULONG, const UNICODE_STRING *, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtCreateKeyTransacted(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, ULONG, const UNICODE_STRING *, ULONG, HANDLE, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtCreateKeyedEvent(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtCreateLowBoxToken(HANDLE *, HANDLE, ACCESS_MASK, OBJECT_ATTRIBUTES *, SID *, ULONG, SID_AND_ATTRIBUTES *, ULONG, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtCreateMailslotFile(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, PIO_STATUS_BLOCK, ULONG, ULONG, ULONG, PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtCreateMutant(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtCreateNamedPipeFile(PHANDLE, ULONG, POBJECT_ATTRIBUTES, PIO_STATUS_BLOCK, ULONG, ULONG, ULONG, ULONG, ULONG, ULONG, ULONG, ULONG, ULONG, PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtCreatePagingFile(PUNICODE_STRING, PLARGE_INTEGER, PLARGE_INTEGER, PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtCreatePort(PHANDLE, POBJECT_ATTRIBUTES, ULONG, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtCreateProcess(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, HANDLE, BOOLEAN, HANDLE, HANDLE, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtCreateProfile(PHANDLE, HANDLE, PVOID, ULONG, ULONG, PVOID, ULONG, KPROFILE_SOURCE, KAFFINITY);
NTSYSAPI NTSTATUS WINAPI NtCreateSection(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *, const LARGE_INTEGER *, ULONG, ULONG, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtCreateSectionEx(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *, const LARGE_INTEGER *, ULONG, ULONG, HANDLE, MEM_EXTENDED_PARAMETER *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtCreateSemaphore(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, LONG, LONG);
NTSYSAPI NTSTATUS WINAPI NtCreateSymbolicLinkObject(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, PUNICODE_STRING);
NTSYSAPI NTSTATUS WINAPI NtCreateThread(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, HANDLE, PCLIENT_ID, PCONTEXT, PINITIAL_TEB, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtCreateThreadEx(HANDLE *, ACCESS_MASK, OBJECT_ATTRIBUTES *, HANDLE, PRTL_THREAD_START_ROUTINE, void *, ULONG, ULONG_PTR, SIZE_T, SIZE_T, PS_ATTRIBUTE_LIST *);
NTSYSAPI NTSTATUS WINAPI NtCreateTimer(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *, TIMER_TYPE);
NTSYSAPI NTSTATUS WINAPI NtCreateToken(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, TOKEN_TYPE, PLUID, PLARGE_INTEGER, PTOKEN_USER, PTOKEN_GROUPS, PTOKEN_PRIVILEGES, PTOKEN_OWNER, PTOKEN_PRIMARY_GROUP, PTOKEN_DEFAULT_DACL, PTOKEN_SOURCE);
NTSYSAPI NTSTATUS WINAPI NtCreateTransaction(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, LPGUID, HANDLE, ULONG, ULONG, ULONG, PLARGE_INTEGER, PUNICODE_STRING);
NTSYSAPI NTSTATUS WINAPI NtCreateUserProcess(HANDLE *, HANDLE *, ACCESS_MASK, ACCESS_MASK, OBJECT_ATTRIBUTES *, OBJECT_ATTRIBUTES *, ULONG, ULONG, RTL_USER_PROCESS_PARAMETERS *, PS_CREATE_INFO *, PS_ATTRIBUTE_LIST *);
NTSYSAPI NTSTATUS WINAPI NtDebugActiveProcess(HANDLE, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtDebugContinue(HANDLE, CLIENT_ID *, NTSTATUS);
NTSYSAPI NTSTATUS WINAPI NtDelayExecution(BOOLEAN, const LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtDeleteAtom(RTL_ATOM);
NTSYSAPI NTSTATUS WINAPI NtDeleteFile(POBJECT_ATTRIBUTES);
NTSYSAPI NTSTATUS WINAPI NtDeleteKey(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtDeleteValueKey(HANDLE, const UNICODE_STRING *);
NTSYSAPI NTSTATUS WINAPI NtDeviceIoControlFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, ULONG, PVOID, ULONG, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtDisplayString(PUNICODE_STRING);
NTSYSAPI NTSTATUS WINAPI NtDuplicateObject(HANDLE, HANDLE, HANDLE, PHANDLE, ACCESS_MASK, ULONG, ULONG);
NTSYSAPI NTSTATUS WINAPI NtDuplicateToken(HANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, BOOLEAN, TOKEN_TYPE, PHANDLE);
NTSYSAPI NTSTATUS WINAPI NtEnumerateKey(HANDLE, ULONG, KEY_INFORMATION_CLASS, void *, DWORD, DWORD *);
NTSYSAPI NTSTATUS WINAPI NtEnumerateValueKey(HANDLE, ULONG, KEY_VALUE_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtExtendSection(HANDLE, PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtFilterToken(HANDLE, ULONG, TOKEN_GROUPS *, TOKEN_PRIVILEGES *, TOKEN_GROUPS *, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtFindAtom(const WCHAR *, ULONG, RTL_ATOM *);
NTSYSAPI NTSTATUS WINAPI NtFlushBuffersFile(HANDLE, IO_STATUS_BLOCK *);
NTSYSAPI NTSTATUS WINAPI NtFlushBuffersFileEx(HANDLE, ULONG, void *, ULONG, IO_STATUS_BLOCK *);
NTSYSAPI NTSTATUS WINAPI NtFlushInstructionCache(HANDLE, LPCVOID, SIZE_T);
NTSYSAPI NTSTATUS WINAPI NtFlushKey(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtFlushProcessWriteBuffers(void);
NTSYSAPI NTSTATUS WINAPI NtFlushVirtualMemory(HANDLE, LPCVOID *, SIZE_T *, IO_STATUS_BLOCK *);
NTSYSAPI NTSTATUS WINAPI NtFlushWriteBuffer(VOID);
NTSYSAPI NTSTATUS WINAPI NtFreeVirtualMemory(HANDLE, PVOID *, SIZE_T *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtFsControlFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, ULONG, PVOID, ULONG, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtGetContextThread(HANDLE, CONTEXT *);
NTSYSAPI ULONG WINAPI NtGetCurrentProcessorNumber(void);
NTSYSAPI ULONG WINAPI NtGetCurrentProcessorNumberEx(PROCESSOR_NUMBER *);
NTSYSAPI NTSTATUS WINAPI NtGetNextProcess(HANDLE, ACCESS_MASK, ULONG, ULONG, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtGetNextThread(HANDLE, HANDLE, ACCESS_MASK, ULONG, ULONG, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtGetNlsSectionPtr(ULONG, ULONG, void *, void **, SIZE_T *);
NTSYSAPI NTSTATUS WINAPI NtGetPlugPlayEvent(ULONG, ULONG, PVOID, ULONG);
NTSYSAPI ULONG WINAPI    NtGetTickCount(VOID);
NTSYSAPI NTSTATUS WINAPI NtGetWriteWatch(HANDLE, ULONG, PVOID, SIZE_T, PVOID *, ULONG_PTR *, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtImpersonateAnonymousToken(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtImpersonateClientOfPort(HANDLE, PLPC_MESSAGE);
NTSYSAPI NTSTATUS WINAPI NtImpersonateThread(HANDLE, HANDLE, PSECURITY_QUALITY_OF_SERVICE);
NTSYSAPI NTSTATUS WINAPI NtInitializeNlsFiles(void **, LCID *, LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtInitializeRegistry(BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtInitiatePowerAction(POWER_ACTION, SYSTEM_POWER_STATE, ULONG, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtIsProcessInJob(HANDLE, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtListenPort(HANDLE, PLPC_MESSAGE);
NTSYSAPI NTSTATUS WINAPI NtLoadDriver(const UNICODE_STRING *);
NTSYSAPI NTSTATUS WINAPI NtLoadKey(const OBJECT_ATTRIBUTES *, OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtLoadKey2(const OBJECT_ATTRIBUTES *, OBJECT_ATTRIBUTES *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtLoadKeyEx(const OBJECT_ATTRIBUTES *, OBJECT_ATTRIBUTES *, ULONG, HANDLE, HANDLE, ACCESS_MASK, HANDLE *, IO_STATUS_BLOCK *);
NTSYSAPI NTSTATUS WINAPI NtLockFile(HANDLE, HANDLE, PIO_APC_ROUTINE, void *, PIO_STATUS_BLOCK, PLARGE_INTEGER, PLARGE_INTEGER, ULONG *, BOOLEAN, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtLockVirtualMemory(HANDLE, PVOID *, SIZE_T *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtMakePermanentObject(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtMakeTemporaryObject(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtMapViewOfSection(HANDLE, HANDLE, PVOID *, ULONG_PTR, SIZE_T, const LARGE_INTEGER *, SIZE_T *, SECTION_INHERIT, ULONG, ULONG);
NTSYSAPI NTSTATUS WINAPI NtMapViewOfSectionEx(HANDLE, HANDLE, PVOID *, const LARGE_INTEGER *, SIZE_T *, ULONG, ULONG, MEM_EXTENDED_PARAMETER *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtNotifyChangeDirectoryFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, PVOID, ULONG, ULONG, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtNotifyChangeKey(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, ULONG, BOOLEAN, PVOID, ULONG, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtNotifyChangeMultipleKeys(HANDLE, ULONG, OBJECT_ATTRIBUTES *, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, ULONG, BOOLEAN, PVOID, ULONG, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtOpenDirectoryObject(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenEvent(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenEventPair(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenFile(PHANDLE FileHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock, ULONG ShareAccess, ULONG OpenOptions);
NTSYSAPI NTSTATUS WINAPI NtOpenIoCompletion(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenJobObject(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenKey(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenKeyEx(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtOpenKeyTransacted(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtOpenKeyTransactedEx(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, ULONG, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtOpenKeyedEvent(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenMutant(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenObjectAuditAlarm(PUNICODE_STRING, PHANDLE, PUNICODE_STRING, PUNICODE_STRING, PSECURITY_DESCRIPTOR, HANDLE, ACCESS_MASK, ACCESS_MASK, PPRIVILEGE_SET, BOOLEAN, BOOLEAN, PBOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtOpenProcess(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *, const CLIENT_ID *);
NTSYSAPI NTSTATUS WINAPI NtOpenProcessToken(HANDLE, DWORD, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtOpenProcessTokenEx(HANDLE, DWORD, DWORD, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtOpenSection(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenSemaphore(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenSymbolicLinkObject(PHANDLE, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtOpenThread(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *, const CLIENT_ID *);
NTSYSAPI NTSTATUS WINAPI NtOpenThreadToken(HANDLE, DWORD, BOOLEAN, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtOpenThreadTokenEx(HANDLE, DWORD, BOOLEAN, DWORD, HANDLE *);
NTSYSAPI NTSTATUS WINAPI NtOpenTimer(HANDLE *, ACCESS_MASK, const OBJECT_ATTRIBUTES *);
NTSYSAPI NTSTATUS WINAPI NtPowerInformation(POWER_INFORMATION_LEVEL, PVOID, ULONG, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtPrivilegeCheck(HANDLE, PPRIVILEGE_SET, PBOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtPrivilegeObjectAuditAlarm(PUNICODE_STRING, HANDLE, HANDLE, ULONG, PPRIVILEGE_SET, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtPrivilegedServiceAuditAlarm(PUNICODE_STRING, PUNICODE_STRING, HANDLE, PPRIVILEGE_SET, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtProtectVirtualMemory(HANDLE, PVOID *, SIZE_T *, ULONG, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtPulseEvent(HANDLE, LONG *);
NTSYSAPI NTSTATUS WINAPI NtQueueApcThread(HANDLE, PNTAPCFUNC, ULONG_PTR, ULONG_PTR, ULONG_PTR);
NTSYSAPI NTSTATUS WINAPI NtQueueApcThreadEx(HANDLE, HANDLE, PNTAPCFUNC, ULONG_PTR, ULONG_PTR, ULONG_PTR);
NTSYSAPI NTSTATUS WINAPI NtQueueApcThreadEx2(HANDLE, HANDLE, ULONG, PNTAPCFUNC, ULONG_PTR, ULONG_PTR, ULONG_PTR);
NTSYSAPI NTSTATUS WINAPI NtQueryAttributesFile(const OBJECT_ATTRIBUTES *, FILE_BASIC_INFORMATION *);
NTSYSAPI NTSTATUS WINAPI NtQueryDefaultLocale(BOOLEAN, LCID *);
NTSYSAPI NTSTATUS WINAPI NtQueryDefaultUILanguage(LANGID *);
NTSYSAPI NTSTATUS WINAPI NtQueryDirectoryFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, PVOID, ULONG, FILE_INFORMATION_CLASS, BOOLEAN, PUNICODE_STRING, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtQueryDirectoryObject(HANDLE, PDIRECTORY_BASIC_INFORMATION, ULONG, BOOLEAN, BOOLEAN, PULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryEaFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG, BOOLEAN, PVOID, ULONG, PULONG, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtQueryEvent(HANDLE, EVENT_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryFullAttributesFile(const OBJECT_ATTRIBUTES *, FILE_NETWORK_OPEN_INFORMATION *);
NTSYSAPI NTSTATUS WINAPI NtQueryInformationAtom(RTL_ATOM, ATOM_INFORMATION_CLASS, PVOID, ULONG, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtQueryInformationFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG, FILE_INFORMATION_CLASS);
NTSYSAPI NTSTATUS WINAPI NtQueryInformationJobObject(HANDLE, JOBOBJECTINFOCLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryInformationPort(HANDLE, PORT_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryInformationProcess(HANDLE, PROCESSINFOCLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryInformationThread(HANDLE, THREADINFOCLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryInformationToken(HANDLE, TOKEN_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryInstallUILanguage(LANGID *);
NTSYSAPI NTSTATUS WINAPI NtQueryIntervalProfile(KPROFILE_SOURCE, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryIoCompletion(HANDLE, IO_COMPLETION_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryKey(HANDLE, KEY_INFORMATION_CLASS, void *, DWORD, DWORD *);
NTSYSAPI NTSTATUS WINAPI NtQueryMultipleValueKey(HANDLE, PKEY_MULTIPLE_VALUE_INFORMATION, ULONG, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryMutant(HANDLE, MUTANT_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryObject(HANDLE, OBJECT_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryOpenSubKeys(POBJECT_ATTRIBUTES, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryPerformanceCounter(PLARGE_INTEGER, PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtQuerySecurityObject(HANDLE, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQuerySection(HANDLE, SECTION_INFORMATION_CLASS, PVOID, SIZE_T, SIZE_T *);
NTSYSAPI NTSTATUS WINAPI NtQuerySemaphore(HANDLE, SEMAPHORE_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQuerySymbolicLinkObject(HANDLE, PUNICODE_STRING, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQuerySystemEnvironmentValue(PUNICODE_STRING, PWCHAR, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQuerySystemEnvironmentValueEx(PUNICODE_STRING, GUID *, void *, ULONG *, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtQuerySystemInformation(SYSTEM_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQuerySystemInformationEx(SYSTEM_INFORMATION_CLASS, void *, ULONG, void *, ULONG, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtQuerySystemTime(PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtQueryTimer(HANDLE, TIMER_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryTimerResolution(PULONG, PULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtQueryValueKey(HANDLE, const UNICODE_STRING *, KEY_VALUE_INFORMATION_CLASS, void *, DWORD, DWORD *);
NTSYSAPI NTSTATUS WINAPI NtQueryLicenseValue(const UNICODE_STRING *, ULONG *, PVOID, ULONG, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtQueryVirtualMemory(HANDLE, LPCVOID, MEMORY_INFORMATION_CLASS, PVOID, SIZE_T, SIZE_T *);
NTSYSAPI NTSTATUS WINAPI NtQueryVolumeInformationFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG, FS_INFORMATION_CLASS);
NTSYSAPI NTSTATUS WINAPI NtRaiseException(PEXCEPTION_RECORD, PCONTEXT, BOOL);
NTSYSAPI NTSTATUS WINAPI NtRaiseHardError(NTSTATUS, ULONG, ULONG, PVOID *, HARDERROR_RESPONSE_OPTION, PHARDERROR_RESPONSE);
NTSYSAPI NTSTATUS WINAPI NtReadFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, PVOID, ULONG, PLARGE_INTEGER, PULONG);
NTSYSAPI NTSTATUS WINAPI NtReadFileScatter(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, FILE_SEGMENT_ELEMENT *, ULONG, PLARGE_INTEGER, PULONG);
NTSYSAPI NTSTATUS WINAPI NtReadRequestData(HANDLE, PLPC_MESSAGE, ULONG, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtReadVirtualMemory(HANDLE, const void *, void *, SIZE_T, SIZE_T *);
NTSYSAPI NTSTATUS WINAPI NtRegisterThreadTerminatePort(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtReleaseKeyedEvent(HANDLE, const void *, BOOLEAN, const LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtReleaseMutant(HANDLE, PLONG);
NTSYSAPI NTSTATUS WINAPI NtReleaseSemaphore(HANDLE, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtRemoveIoCompletion(HANDLE, PULONG_PTR, PULONG_PTR, PIO_STATUS_BLOCK, PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtRemoveIoCompletionEx(HANDLE, FILE_IO_COMPLETION_INFORMATION *, ULONG, ULONG *, LARGE_INTEGER *, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtRemoveProcessDebug(HANDLE, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtRenameKey(HANDLE, UNICODE_STRING *);
NTSYSAPI NTSTATUS WINAPI NtReplaceKey(POBJECT_ATTRIBUTES, HANDLE, POBJECT_ATTRIBUTES);
NTSYSAPI NTSTATUS WINAPI NtReplyPort(HANDLE, PLPC_MESSAGE);
NTSYSAPI NTSTATUS WINAPI NtReplyWaitReceivePort(HANDLE, PULONG, PLPC_MESSAGE, PLPC_MESSAGE);
NTSYSAPI NTSTATUS WINAPI NtReplyWaitReceivePortEx(HANDLE, PULONG, PLPC_MESSAGE, PLPC_MESSAGE, PLARGE_INTEGER);
NTSYSAPI NTSTATUS WINAPI NtReplyWaitReplyPort(HANDLE, PLPC_MESSAGE);
NTSYSAPI NTSTATUS WINAPI NtRequestPort(HANDLE, PLPC_MESSAGE);
NTSYSAPI NTSTATUS WINAPI NtRequestWaitReplyPort(HANDLE, PLPC_MESSAGE, PLPC_MESSAGE);
NTSYSAPI NTSTATUS WINAPI NtResetEvent(HANDLE, LONG *);
NTSYSAPI NTSTATUS WINAPI NtResetWriteWatch(HANDLE, PVOID, SIZE_T);
NTSYSAPI NTSTATUS WINAPI NtRestoreKey(HANDLE, HANDLE, ULONG);
NTSYSAPI NTSTATUS WINAPI NtResumeProcess(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtResumeThread(HANDLE, PULONG);
NTSYSAPI NTSTATUS WINAPI NtRollbackTransaction(HANDLE, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtSaveKey(HANDLE, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSecureConnectPort(PHANDLE, PUNICODE_STRING, PSECURITY_QUALITY_OF_SERVICE, PLPC_SECTION_WRITE, PSID, PLPC_SECTION_READ, PULONG, PVOID, PULONG);
NTSYSAPI NTSTATUS WINAPI NtSetContextThread(HANDLE, const CONTEXT *);
NTSYSAPI NTSTATUS WINAPI NtSetDebugFilterState(ULONG, ULONG, BOOLEAN);
NTSYSAPI NTSTATUS WINAPI NtSetDefaultHardErrorPort(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSetDefaultLocale(BOOLEAN, LCID);
NTSYSAPI NTSTATUS WINAPI NtSetDefaultUILanguage(LANGID);
NTSYSAPI NTSTATUS WINAPI NtSetEaFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetEvent(HANDLE, LONG *);
NTSYSAPI NTSTATUS WINAPI NtSetEventBoostPriority(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSetHighEventPair(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSetHighWaitLowEventPair(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSetHighWaitLowThread(VOID);
NTSYSAPI NTSTATUS WINAPI NtSetInformationDebugObject(HANDLE, DEBUGOBJECTINFOCLASS, PVOID, ULONG, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtSetInformationFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG, FILE_INFORMATION_CLASS);
NTSYSAPI NTSTATUS WINAPI NtSetInformationJobObject(HANDLE, JOBOBJECTINFOCLASS, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetInformationKey(HANDLE, const int, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetInformationObject(HANDLE, OBJECT_INFORMATION_CLASS, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetInformationProcess(HANDLE, PROCESSINFOCLASS, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetInformationThread(HANDLE, THREADINFOCLASS, LPCVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetInformationToken(HANDLE, TOKEN_INFORMATION_CLASS, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetInformationVirtualMemory(HANDLE, VIRTUAL_MEMORY_INFORMATION_CLASS, ULONG_PTR, PMEMORY_RANGE_ENTRY, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetIntervalProfile(ULONG, KPROFILE_SOURCE);
NTSYSAPI NTSTATUS WINAPI NtSetIoCompletion(HANDLE, ULONG_PTR, ULONG_PTR, NTSTATUS, SIZE_T);
NTSYSAPI NTSTATUS WINAPI NtSetIoCompletionEx(HANDLE, HANDLE, ULONG_PTR, ULONG_PTR, NTSTATUS, SIZE_T);
NTSYSAPI NTSTATUS WINAPI NtSetLdtEntries(ULONG, ULONG, ULONG, ULONG, ULONG, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetLowEventPair(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSetLowWaitHighEventPair(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSetLowWaitHighThread(VOID);
NTSYSAPI NTSTATUS WINAPI NtSetSecurityObject(HANDLE, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR);
NTSYSAPI NTSTATUS WINAPI NtSetSystemEnvironmentValue(PUNICODE_STRING, PUNICODE_STRING);
NTSYSAPI NTSTATUS WINAPI NtSetSystemInformation(SYSTEM_INFORMATION_CLASS, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetSystemPowerState(POWER_ACTION, SYSTEM_POWER_STATE, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetSystemTime(const LARGE_INTEGER *, LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtSetThreadExecutionState(EXECUTION_STATE, EXECUTION_STATE *);
NTSYSAPI NTSTATUS WINAPI NtSetTimer(HANDLE, const LARGE_INTEGER *, PTIMER_APC_ROUTINE, PVOID, BOOLEAN, ULONG, BOOLEAN *);
NTSYSAPI NTSTATUS WINAPI NtSetTimerResolution(ULONG, BOOLEAN, PULONG);
NTSYSAPI NTSTATUS WINAPI NtSetValueKey(HANDLE, const UNICODE_STRING *, ULONG, ULONG, const void *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtSetVolumeInformationFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG, FS_INFORMATION_CLASS);
NTSYSAPI NTSTATUS WINAPI NtSignalAndWaitForSingleObject(HANDLE, HANDLE, BOOLEAN, const LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtShutdownSystem(SHUTDOWN_ACTION);
NTSYSAPI NTSTATUS WINAPI NtStartProfile(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtStopProfile(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSuspendProcess(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtSuspendThread(HANDLE, PULONG);
NTSYSAPI NTSTATUS WINAPI NtSystemDebugControl(SYSDBG_COMMAND, PVOID, ULONG, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtTerminateJobObject(HANDLE, NTSTATUS);
NTSYSAPI NTSTATUS WINAPI NtTerminateProcess(HANDLE, LONG);
NTSYSAPI NTSTATUS WINAPI NtTerminateThread(HANDLE, LONG);
NTSYSAPI NTSTATUS WINAPI NtTestAlert(VOID);
NTSYSAPI NTSTATUS WINAPI NtTraceControl(ULONG, void *, ULONG, void *, ULONG, ULONG *);
NTSYSAPI NTSTATUS WINAPI NtUnloadDriver(const UNICODE_STRING *);
NTSYSAPI NTSTATUS WINAPI NtUnloadKey(POBJECT_ATTRIBUTES);
NTSYSAPI NTSTATUS WINAPI NtUnloadKeyEx(POBJECT_ATTRIBUTES, HANDLE);
NTSYSAPI NTSTATUS WINAPI NtUnlockFile(HANDLE, PIO_STATUS_BLOCK, PLARGE_INTEGER, PLARGE_INTEGER, PULONG);
NTSYSAPI NTSTATUS WINAPI NtUnlockVirtualMemory(HANDLE, PVOID *, SIZE_T *, ULONG);
NTSYSAPI NTSTATUS WINAPI NtUnmapViewOfSection(HANDLE, PVOID);
NTSYSAPI NTSTATUS WINAPI NtUnmapViewOfSectionEx(HANDLE, PVOID, ULONG);
NTSYSAPI NTSTATUS WINAPI NtVdmControl(ULONG, PVOID);
NTSYSAPI NTSTATUS WINAPI NtWaitForAlertByThreadId(const void *, const LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtWaitForDebugEvent(HANDLE, BOOLEAN, LARGE_INTEGER *, DBGUI_WAIT_STATE_CHANGE *);
NTSYSAPI NTSTATUS WINAPI NtWaitForKeyedEvent(HANDLE, const void *, BOOLEAN, const LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtWaitForSingleObject(HANDLE, BOOLEAN, const LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtWaitForMultipleObjects(ULONG, const HANDLE *, WAIT_TYPE, BOOLEAN, const LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI NtWaitHighEventPair(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtWaitLowEventPair(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtWorkerFactoryWorkerReady(HANDLE);
NTSYSAPI NTSTATUS WINAPI NtWriteFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, const void *, ULONG, PLARGE_INTEGER, PULONG);
NTSYSAPI NTSTATUS WINAPI NtWriteFileGather(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, FILE_SEGMENT_ELEMENT *, ULONG, PLARGE_INTEGER, PULONG);
NTSYSAPI NTSTATUS WINAPI NtWriteRequestData(HANDLE, PLPC_MESSAGE, ULONG, PVOID, ULONG, PULONG);
NTSYSAPI NTSTATUS WINAPI NtWriteVirtualMemory(HANDLE, void *, const void *, SIZE_T, SIZE_T *);
NTSYSAPI NTSTATUS WINAPI NtYieldExecution(void);

NTSYSAPI NTSTATUS WINAPI TpAllocCleanupGroup(TP_CLEANUP_GROUP **);
NTSYSAPI NTSTATUS WINAPI TpAllocIoCompletion(TP_IO **, HANDLE, PTP_IO_CALLBACK, void *, TP_CALLBACK_ENVIRON *);
NTSYSAPI NTSTATUS WINAPI TpAllocPool(TP_POOL **, PVOID);
NTSYSAPI NTSTATUS WINAPI TpAllocTimer(TP_TIMER **, PTP_TIMER_CALLBACK, PVOID, TP_CALLBACK_ENVIRON *);
NTSYSAPI NTSTATUS WINAPI TpAllocWait(TP_WAIT **, PTP_WAIT_CALLBACK, PVOID, TP_CALLBACK_ENVIRON *);
NTSYSAPI NTSTATUS WINAPI TpAllocWork(TP_WORK **, PTP_WORK_CALLBACK, PVOID, TP_CALLBACK_ENVIRON *);
NTSYSAPI void WINAPI TpCallbackLeaveCriticalSectionOnCompletion(TP_CALLBACK_INSTANCE *, RTL_CRITICAL_SECTION *);
NTSYSAPI NTSTATUS WINAPI TpCallbackMayRunLong(TP_CALLBACK_INSTANCE *);
NTSYSAPI void WINAPI TpCallbackReleaseMutexOnCompletion(TP_CALLBACK_INSTANCE *, HANDLE);
NTSYSAPI void WINAPI TpCallbackReleaseSemaphoreOnCompletion(TP_CALLBACK_INSTANCE *, HANDLE, DWORD);
NTSYSAPI void WINAPI TpCallbackSetEventOnCompletion(TP_CALLBACK_INSTANCE *, HANDLE);
NTSYSAPI void WINAPI TpCallbackUnloadDllOnCompletion(TP_CALLBACK_INSTANCE *, HMODULE);
NTSYSAPI void WINAPI TpCancelAsyncIoOperation(TP_IO *);
NTSYSAPI void WINAPI TpDisassociateCallback(TP_CALLBACK_INSTANCE *);
NTSYSAPI BOOL WINAPI TpIsTimerSet(TP_TIMER *);
NTSYSAPI void WINAPI TpPostWork(TP_WORK *);
NTSYSAPI NTSTATUS WINAPI TpQueryPoolStackInformation(TP_POOL *, TP_POOL_STACK_INFORMATION *stack_info);
NTSYSAPI void WINAPI TpReleaseCleanupGroup(TP_CLEANUP_GROUP *);
NTSYSAPI void WINAPI TpReleaseCleanupGroupMembers(TP_CLEANUP_GROUP *, BOOL, PVOID);
NTSYSAPI void WINAPI TpReleaseIoCompletion(TP_IO *);
NTSYSAPI void WINAPI TpReleasePool(TP_POOL *);
NTSYSAPI void WINAPI TpReleaseTimer(TP_TIMER *);
NTSYSAPI void WINAPI TpReleaseWait(TP_WAIT *);
NTSYSAPI void WINAPI TpReleaseWork(TP_WORK *);
NTSYSAPI void WINAPI TpSetPoolMaxThreads(TP_POOL *, DWORD);
NTSYSAPI BOOL WINAPI TpSetPoolMinThreads(TP_POOL *, DWORD);
NTSYSAPI NTSTATUS WINAPI TpSetPoolStackInformation(TP_POOL *, TP_POOL_STACK_INFORMATION *stack_info);
NTSYSAPI void WINAPI TpSetTimer(TP_TIMER *, LARGE_INTEGER *, LONG, LONG);
NTSYSAPI void WINAPI TpSetWait(TP_WAIT *, HANDLE, LARGE_INTEGER *);
NTSYSAPI NTSTATUS WINAPI TpSimpleTryPost(PTP_SIMPLE_CALLBACK, PVOID, TP_CALLBACK_ENVIRON *);
NTSYSAPI void WINAPI TpStartAsyncIoOperation(TP_IO *);
NTSYSAPI void WINAPI TpWaitForIoCompletion(TP_IO *, BOOL);
NTSYSAPI void WINAPI TpWaitForTimer(TP_TIMER *, BOOL);
NTSYSAPI void WINAPI TpWaitForWait(TP_WAIT *, BOOL);
NTSYSAPI void WINAPI TpWaitForWork(TP_WORK *, BOOL);
#ifdef __ms_va_list
NTSYSAPI NTSTATUS WINAPI vDbgPrintEx(ULONG, ULONG, LPCSTR, __ms_va_list);
NTSYSAPI NTSTATUS WINAPI vDbgPrintExWithPrefix(LPCSTR, ULONG, ULONG, LPCSTR, __ms_va_list);
#endif

/* 32-bit or 64-bit only functions */

#ifdef WINE_UNIX_LIB
NTSYSAPI NTSTATUS WINAPI PsCreateSystemThread(PHANDLE, ULONG, POBJECT_ATTRIBUTES, HANDLE, PCLIENT_ID, PRTL_THREAD_START_ROUTINE, PVOID);
NTSYSAPI HANDLE WINAPI PsGetCurrentProcessId(void);
NTSYSAPI HANDLE WINAPI PsGetCurrentThreadId(void);
NTSYSAPI NTSTATUS WINAPI PsTerminateSystemThread(NTSTATUS);
#endif

/***********************************************************************
 * Inline functions
 */

#define NtCurrentProcess() ((HANDLE) ~(ULONG_PTR)0)
#define NtCurrentThread()  ((HANDLE) ~(ULONG_PTR)1)

/* list manipulation macros */
#define InitializeListHead(le) (void)((le)->Flink = (le)->Blink = (le))
#define InsertHeadList(le, e)        \
    do                               \
    {                                \
        PLIST_ENTRY f = (le)->Flink; \
        (e)->Flink    = f;           \
        (e)->Blink    = (le);        \
        f->Blink      = (e);         \
        (le)->Flink   = (e);         \
    } while (0)
#define InsertTailList(le, e)        \
    do                               \
    {                                \
        PLIST_ENTRY b = (le)->Blink; \
        (e)->Flink    = (le);        \
        (e)->Blink    = b;           \
        b->Flink      = (e);         \
        (le)->Blink   = (e);         \
    } while (0)
#define IsListEmpty(le) ((le)->Flink == (le))
#define RemoveEntryList(e)                          \
    do                                              \
    {                                               \
        PLIST_ENTRY f = (e)->Flink, b = (e)->Blink; \
        f->Blink   = b;                             \
        b->Flink   = f;                             \
        (e)->Flink = (e)->Blink = NULL;             \
    } while (0)

static inline PLIST_ENTRY RemoveHeadList(PLIST_ENTRY le)
{
    PLIST_ENTRY f, b, e;

    e        = le->Flink;
    f        = le->Flink->Flink;
    b        = le->Flink->Blink;
    f->Blink = b;
    b->Flink = f;

    if (e != le)
    {
        e->Flink = e->Blink = NULL;
    }
    return e;
}

static inline PLIST_ENTRY RemoveTailList(PLIST_ENTRY le)
{
    PLIST_ENTRY f, b, e;

    e        = le->Blink;
    f        = le->Blink->Flink;
    b        = le->Blink->Blink;
    f->Blink = b;
    b->Flink = f;

    if (e != le)
    {
        e->Flink = e->Blink = NULL;
    }
    return e;
}

