/* AUTO-GENERATED FILE - DO NOT EDIT BY HAND
 * Generated from config/config.env by gen_config.sh
 */
#pragma once

#define CONFIG_TARGET 64
#define CONFIG_ARCH "x86_64"
#define CONFIG_IMAGETYPE "disk"
#define CONFIG_IMAGEFS "fat32"
#define CONFIG_IMAGESIZE "250m"
#define CONFIG_TOOLCHAIN "../.toolchains"
#define CONFIG_MAX_PATH_LENGTH 512
#define CONFIG_MOUNTMETHOD "mount"
#define CONFIG_USE_BIOS 1
#define CONFIG_ENABLE_MULTI_CORE 1
#define CONFIG_ENABLE_PAGING 1
#define CONFIG_USE_EAGER_FORK 0
#define CONFIG_MODULE_BSW 1
#define CONFIG_MODULE_LA57 0
#define CONFIG_INCLUDE_MLFQ 1
#define CONFIG_SCHED_ALGORITHM "MLFQ"
#define CONFIG_USE_LEVEL_1 1
#define CONFIG_USE_LEVEL_2 1
#define CONFIG_USE_LEVEL_3 1
#define CONFIG_USE_LEVEL_4 1
#define CONFIG_USE_LEVEL_5 1
